# These are supported funding model platforms

github: oerdnj
patreon: oerdnj
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=ondrej%40sury%2eorg&lc=CZ&item_name=DEB%2eSURY%2eORG&item_number=DEB%2eSURY%2eORG&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted', 'https://www.blockchain.com/btc/address/15WRQCrVHWUdcn3sbT7PF6u2FJGfbb8GW5']
